hide_download: true
hide_download_original: null
leftnav:
- identifier: 90ee83d8-cf33-3ff8-8e08-c3bd113309e9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e99067b3-60b9-072e-c48c-a3b7473dd38d
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 5928fec7-993f-eb85-0b7d-76b0af816321
  name: Homework
  pageRef: /pages/homework
  weight: 30
- identifier: 64c4a530-fd05-1a23-c074-9597bb86f5f5
  name: Exams
  pageRef: /pages/exams
  weight: 40
- identifier: 6bb74e27-b4f0-7d51-e924-5b62085c1957
  name: Projects
  pageRef: /pages/projects
  weight: 50
- identifier: cf6e51e7-8803-cdbb-76d9-8fa749ad53f2
  name: Video Lectures
  pageRef: /video_galleries/video-lectures
  weight: 60
- identifier: 1a751b6e-10d6-5ddc-de46-19f6302c0105
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 70
